---
name: MeshCentral
version: 0.1.17
slug: meshcentral
description: Web-based remote computer management server
url: https://github.com/Ylianst/MeshCentral
startup: system
init: false
timeout: 30
arch:
  - aarch64
  - amd64
map:
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  meshcentral_config: str?
ports:
  443/tcp: 443
  80/tcp: 80
  44330/tcp: 44330
  453/tcp: 453
  1234/tcp: 1234
ports_description:
  443/tcp: MeshCentral HTTPS port
  80/tcp: MeshCentral HTTP redirect port
  44330/tcp: MeshCentral MPS port
  453/tcp: MeshCentral relay port
  1234/tcp: MeshCentral agent port
