---
name: MeshCentral
version: 0.1.14
slug: meshcentral
description: Web-based remote computer management server
url: https://github.com/Ylianst/MeshCentral
startup: system
init: false
timeout: 30
arch:
  - aarch64
  - amd64
map:
  - share:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  meshcentral_config: str?
ports:
  44433/tcp: 44433
  44431/tcp: 44431
  44432/tcp: 44432
ports_description:
  44433/tcp: MeshCentral HTTPS port
  44431/tcp: MeshCentral redirect port
  44432/tcp: MeshCentral MPS port
